### ISSUE TITLE
Multiple packages allow `solana-program@2`

### ISSUE THREAD

**Issue by Buzzec** [anza-xyz/agave#1869]
#### Problem
`spl-discriminator@0.1.1`, `spl-pod@0.1.1`, `spl-program-error@0.3.1`, `spl-tlv-account-resolution@0.5.2`, and `spl-type-length-value@0.3.1` all depend on `solana-program` with
```toml
[dependencies.solana-program]
version = ">=1.17.17,<=2"
```

This is incorrect because it allows `solana-program@2`.

This should be 
```toml
[dependencies.solana-program]
version = ">=1.17.17,<2"
```

`solana-client@<2` requires these packages and cannot be used anymore. `solana-client@>=2` contains compile errors.

#### Proposed Solution
Yank all crates that could rely on `solana-program@2` now that it's published.

#### Workaround
You can get the lock file to not use `solana-program@2` if you first add `solana-sdk`, build, and then add `solana-client`. This is a very fickle solution and could break whenever a new update is pushed to any crate.
