### ISSUE TITLE
Issue with setting cargo dependency to point to GitHub reference

### ISSUE THREAD

**Issue by Eduard-Voiculescu** [anza-xyz/agave#3752]
Hi, I have found an interesting issue.

### Steps to reproduce:
```bash
cargo init
```

Change the generated `Cargo.Toml` with this one:
```bash
[package]
name = "agave"
version = "0.1.0"
edition = "2021"

[dependencies]
agave-geyser-plugin-interface = { git = "https://github.com/anza-xyz/agave.git", tag = "v2.0.16" }
#agave-geyser-plugin-interface = "2.0.10"
```

Uncommenting the second agave-geyser-plugin-interface build as expected. But if I let the first line, which points to the repo of where the dependency lives. I get a bunch of compilation issues.

I have tried multiple rust version, notably the one set inside of the `rust-toolchain.toml` (1.81).

**Comment by joncinque** [comment]
The git repo does some crate patching to make the build work at https://github.com/anza-xyz/agave/blob/31742ca61e7eff18570d7987b3fc7af9050d3303/Cargo.toml#L632

As a quick fix, you simply need to patch solana-program, so add the following to your Cargo.toml:

```
[patch.crates-io]
solana-program = { git = "https://github.com/anza-xyz/agave.git", tag = "v2.0.16" }
```

Be sure to clear your lockfile beforehand.

**Comment by Eduard-Voiculescu** [comment]
Ok so I added the patch  and cleared my lock file. But I still see a lot of errors and notably this message:

```bash
perhaps two different versions of crate `solana_program` are being used?
```

I run these commands

```bash
rm Cargo.Lock
cargo update
cargo build # check gives me the same output
```

Is there anything missing? 

My cargo.toml looks like this
```toml
[package]
name = "agave"
version = "0.1.0"
edition = "2021"

[dependencies]
agave-geyser-plugin-interface = { git = "https://github.com/anza-xyz/agave.git", tag = "v2.0.16" }

[patch.crates-io]
solana-program = { git = "https://github.com/anza-xyz/agave.git", tag = "v2.0.16" }
```
