### ISSUE TITLE
Circular dependency between `solana-sdk`, `solana-stake-interface`, and `solana-system-interface`

### ISSUE THREAD

**Issue by vovkman** [anza-xyz/agave#4840]
#### Problem
There is now a circular dependency between `solana-sdk`, `solana-stake-interface`, and `solana-system-interface`. 

I have resolved this by putting the repos for `solana-stake-interface` and `solana-system-interface` back into agave, which is less than ideal. The crates need to be restructured to prevent this from happening

#### Proposed Solution

Break the circular dependency or put the crates back into agave

#### Repro steps
Create a trivial rust project with the following Cargo.toml

```toml
[package]
name = "dep-issue"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { git = "https://github.com/anza-xyz/agave", branch = "master" }
```

run `cargo build`
