### ISSUE TITLE
Issue with `subtle` dependency 

### ISSUE THREAD

**Issue by de-ltd** [anza-xyz/agave#612]
stdout : error: failed to select a version for subtle.
... required by package rustls v0.22.0
... which satisfies dependency rustls = "^0.22" of package tokio-rustls v0.25.0
... which satisfies dependency tokio-rustls = "^0.25" of package jsonrpsee-client-transport v0.21.0
... which satisfies dependency jsonrpsee-client-transport = "^0.21.0" of package jsonrpsee-ws-client v0.21.0
... which satisfies dependency jsonrpsee-ws-client = "^0.21.0" of package jsonrpsee v0.21.0
... which satisfies dependency jsonrpsee = "^0.21.0" (locked to 0.21.0) of package prog v0.1.0  versions that meet the requirements ^2.5.0` are: 2.5.0

all possible versions conflict with previously selected packages.

previously selected package subtle v2.4.1
... which satisfies dependency subtle = "^2.2.1" (locked to 2.4.1) of package curve25519-dalek v3.2.1 (https://github.com/solana-labs/curve25519-dalek.git?rev=c14774464c4d38de553c6ef2f48a10982c1b4801#c1477446)
... which satisfies dependency curve25519-dalek = "^3.2.1" (locked to 3.2.1) of package solana-program v1.18.9
... which satisfies dependency solana-program = "^1.18.9" (locked to 1.18.9) of package `prog v0.1.0

failed to select a version for subtle which could resolve this conflict

**Comment by ivs** [comment]
Hey! Google brought me here:)

I figured out this problem by tracking down rustls deps in solana and reqwest version:
https://github.com/solana-labs/solana/blob/27eff8408b7223bb3c4ab70523f8a8dca3ca6645/Cargo.toml#L289
https://crates.io/crates/reqwest/0.11.27/dependencies

This one worked for me:
`reqwest = { version = "0.11.27", default-features = false, features = ["json", "rustls-tls"] }
`

It's important to disable default-features, otherwise reqwest still linked to openssl.
With rustls app can be build from scratch docker image, without openssl dependency hell:
```Dockerfile
FROM lukemathwalker/cargo-chef:latest-rust-alpine as chef
WORKDIR /app

FROM chef AS planner
COPY ./Cargo.toml ./Cargo.lock ./
COPY ./src ./src
RUN cargo chef prepare

FROM chef AS builder
COPY --from=planner /app/recipe.json .
RUN cargo chef cook --release
COPY . .
RUN cargo build --release
RUN cp ./target/release/pools ./app
RUN ls -lah ./app

FROM scratch AS runtime
WORKDIR /
ENV RUST_LOG=info
COPY --from=builder /app/app /
ENTRYPOINT ["/app"]
```
Just 80mb image.

**Comment by ivs** [comment]
Addition of tokio-tungstenite forced me to patch deps, at least `zeroize` to 1.6.0
Precise versions + patched deps:
```Toml
reqwest = { version = "0.11.27", default-features = false, features = ["json", "rustls-tls"] }
tokio-tungstenite = { version = "0.20.1", features = ["rustls"] }

[patch.crates-io]
curve25519-dalek = { git = 'https://github.com/ivs/curve25519-dalek', branch='rustls-dep-hell' }
aes-gcm-siv = { git = 'https://github.com/ivs/AEADs', branch='rustls-dep-hell' }
```
Also `solana-zk-token-sdk` should be explicitly set to solana-client/sdk version.

And solana-zk-token-sdk is exactly the root cause of rustls dephell, it would be nice to update versions:
aes-gcm-siv to have subtle >=2.5.0 and zeroize >=1.6.0
curve25519-dalek to have zeroize >=1.6.0

It will unlock rustls 22.1.* deps, and it looks like zeroize >= 1.7.0 will help with 22.2.*.
