### ISSUE TITLE
Critical Version Inconsistency Across Solana/Agave Crates - Geyser Interface Lagging Behind

### ISSUE THREAD

**Issue by pionoor** [anza-xyz/agave#6359]
### Problem Description

There is a critical version inconsistency across the Solana/Agave ecosystem crates. While the latest Agave client release is v2.2.14, related crates are scattered across different versions, with some at parity and others severely outdated. **Most critically, the agave-geyser-plugin-interface is stuck at v2.2.7 - 7 versions behind!**

### Current State - Version Fragmentation

In a project using the Solana Geyser plugin, the following version disparities are observed:

```toml
# Latest agave-client is at 2.2.14

# AT PARITY with latest (2.2.14)
solana-measure = { version = "=2.2.14" }                 # ✓ Current
solana-metrics = { version = "=2.2.14" }                 # ✓ Current

# BEHIND latest (2.2.14)
agave-geyser-plugin-interface = { version = "=2.2.7" }  # 7 versions BEHIND - CRITICAL!
solana-client = "=2.2.7"                                 # 7 versions behind
solana-account-decoder = { version = "=2.2.7" }         # 7 versions behind
solana-transaction-status = { version = "=2.2.7" }      # 7 versions behind

# SEVERELY BEHIND
solana-logger = { version = "=2.2.1" }                   # 13 versions behind!
solana-sdk = { version = "=2.2.2" }                      # 12 versions behind!
```

This creates a **13-version spread** across the ecosystem (2.2.1 to 2.2.14)!

### Critical Issue: Geyser Interface

**The agave-geyser-plugin-interface being stuck at v2.2.7 while agave-client is at v2.2.14 is a critical blocker** because:

1. **7 versions behind** means missing months of updates, features, and fixes
2. Geyser plugins are essential infrastructure for:
   - RPC providers
   - Indexers
   - Analytics platforms
   - Trading systems
3. Plugin developers cannot leverage features from the last 7 agave-client releases
4. Potential compatibility issues between the outdated plugin interface and current runtime
5. Security patches and performance improvements from 7 releases are unavailable

### Why This Matters

The Geyser interface is not just another crate - it's the **primary integration point** for external systems to stream Solana data. Having it 7 versions behind while some crates are current creates:

- **API Mismatches**: Features available in agave-client 2.2.14 cannot be exposed through the 2.2.7 interface
- **Type Incompatibilities**: Struct changes between versions cause compilation failures
- **Performance Gaps**: Optimizations in newer versions cannot be utilized
- **Security Risks**: Known vulnerabilities in older versions remain unpatched

### Expected Behavior

All Solana/Agave crates should be released in lockstep. When agave-client v2.2.14 is released:
- agave-geyser-plugin-interface v2.2.14 should be released simultaneously
- All solana-* crates should be updated to v2.2.14
- No crate should be released independently

### Immediate Action Required

1. **URGENT - Priority 0**: Update `agave-geyser-plugin-interface` to v2.2.14 immediately
   - This is blocking production systems
   - Should be treated as a critical release

2. **Priority 1**: Bring all lagging crates to v2.2.14:
   - solana-client
   - solana-account-decoder
   - solana-transaction-status
   - solana-sdk
   - solana-logger

3. **Priority 2**: Implement process to prevent future divergence

### Current Blockers

Teams building on Solana are forced to:
- Use outdated Geyser interfaces missing critical features
- Mix incompatible versions hoping they work
- Implement workarounds for missing functionality
- Accept security vulnerabilities in older versions

### Call to Action

**The agave-geyser-plugin-interface must be brought to v2.2.14 immediately.** This is not a nice-to-have - it's blocking critical infrastructure development across the Solana ecosystem.

Every day this remains unfixed, developers are:
- Unable to build modern Geyser plugins
- Forced to use outdated and potentially insecure code
- Wasting time on version compatibility instead of building

---

**Please treat the geyser interface update as a critical priority. The 7-version gap is unacceptable for such a fundamental integration point.**
