### ISSUE TITLE
misleading names of `profile`s

### ISSUE THREAD

**Issue by sonicfromnewyoke** [anza-xyz/agave#6500]
#### Problem

there are 2 misleading profiles
1. release
2. release-with-lto

both of them has set `lto = "thin"`, so actually profile that now has name `release`  is `release-with-lto`. And another one, that now has name `release-with-lto` has `codegen-units = 1` and behaves as `release-with-single-codegeen-unit`.

also profile named `release-with-lto` has unesassary duplicated fields:
```toml
split-debuginfo = "unpacked"
lto = "thin"
```
which has already were inherited from `release`, so `release-with-lto` can be simplified to:
```toml
[profile.release-with-lto]
inherits = "release"
codegen-units = 1
```

#### Proposed Solution

renaming profile `release-with-lto` to either something what really represents difference from the inherited `release` profile like `release-with-single-codegen-unit` or using something more abstract like it was done by **reth** team and their [maxperf](https://github.com/paradigmxyz/reth/blob/main/Cargo.toml#L313-L316) profile
